// This file was autogenerated by /Users/agaber/Workspace/chatapp/lib/main/javascript/closure-library/closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('../../../../../../src/main/javascript/snaps/chatapp/main.js', ['snaps.chatapp'], []);
goog.addDependency('../../../../../../src/main/javascript/snaps/chatapp/test/phone_controller.js', ['snaps.chatapp.test.PhoneController'], []);
