/**
 * @fileoverview The "main" javascript file of the application. Any code needed
 * should be required here. Ideally this file will just load up the main module
 * which itself can pull in the dependencies it needs.
 * 
 * Some notes:
 * -- This file should have the same name as the maven project's artifactId
 * -- deps.js is autogenerated by the maven script and only needed when using
 *    uncompiled javascript code, presumably for test or local development 
 *    purposes.
 * -- Most of the files in goog/ have special purposes. Don't mess with them.
 */

goog.require('acme.sandbox.algorithms');
goog.require('acme.sandbox.PhoneController');
goog.require('acme.sandbox.widgets');
