// This file was autogenerated by closure/depswriter.py.
// Please do not edit.
goog.addDependency('goog/export.js', ['goog'], []);
goog.addDependency('goog/goog.js', ['goog'], []);
goog.addDependency('jquery/jquery-1.7.2.js', ['jquery'], []);
goog.addDependency('snaps/chatapp/sandbox/algorithms.js', ['snaps.chatapp.sandbox.algorithms'], ['underscore']);
goog.addDependency('snaps/chatapp/sandbox/phone_controller.js', ['snaps.chatapp.sandbox.PhoneController'], []);
goog.addDependency('snaps/chatapp/sandbox/phone_widgets.js', ['snaps.chatapp.sandbox.widgets'], ['jquery']);
goog.addDependency('underscore/underscore-1.3.2.js', ['underscore'], []);
